language: c++
sudo: false

matrix:
  include:
    - env: COMPILER=clang++-3.8 STDLIB=libc++ CONFIGURATION=Debug FLAGS="-fsanitize=address"
      addons: &clang38
        apt:
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages: clang-3.8

    - env: COMPILER=clang++-3.8 STDLIB=libc++ CONFIGURATION=Release BENCHMARK=true
      addons: *clang38

    - env: COMPILER=g++-6 CONFIGURATION=Debug
      addons: &gcc6
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-6

    - env: COMPILER=g++-6 CONFIGURATION=Release BENCHMARK=true
      addons: *gcc6

install:
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  # Install a recent CMake
  - CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
  - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

  # Install boost
  - BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz"
  - mkdir boost && travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C boost
  - export BOOST_PATH=${DEPS_DIR}/boost

  # Install libc++ and libc++abi
  - |
    if [[ "${STDLIB}" == "libc++" ]]; then
      VERSION=3.8.0
      LLVM_URL="http://llvm.org/releases/${VERSION}/llvm-${VERSION}.src.tar.xz"
      LIBCXX_URL="http://llvm.org/releases/${VERSION}/libcxx-${VERSION}.src.tar.xz"
      LIBCXXABI_URL="http://llvm.org/releases/${VERSION}/libcxxabi-${VERSION}.src.tar.xz"
      mkdir -p llvm llvm/build llvm/projects/libcxx llvm/projects/libcxxabi
      travis_retry wget --quiet -O - ${LLVM_URL} | tar --strip-components=1 -xJ -C llvm
      travis_retry wget --quiet -O - ${LIBCXX_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxx
      travis_retry wget --quiet -O - ${LIBCXXABI_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxxabi
      (cd llvm/build && cmake .. -DCMAKE_CXX_COMPILER=clang++ && make cxxabi cxx -j2)
      export CXXFLAGS="-Wno-reserved-id-macro \
                       -I ${DEPS_DIR}/llvm/build/include \
                       -I ${DEPS_DIR}/llvm/build/include/c++/v1 \
                       -stdlib=libc++"
      export LDFLAGS="-L ${DEPS_DIR}/llvm/build/lib -l c++ -l c++abi"
      export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/llvm/build/lib"
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - ${COMPILER} --version
  - |
    cmake .. -DCMAKE_CXX_COMPILER=${COMPILER} \
             -DCMAKE_CXX_FLAGS="${CXXFLAGS} ${FLAGS}" \
             -DCMAKE_BUILD_TYPE=${CONFIGURATION} \
             -DCHECK_BENCHMARKS=${BENCHMARK} \
             -DBOOST_ROOT=${BOOST_PATH}
  - make deps-test
  - test "${BENCHMARK}" == true && make deps-benchmark || true

script:
  - make check
  - |
    if [["${BENCHMARK}" == true ]]; then
       	chmod 600 ../tools/ssh-key
        scp -o StrictHostKeyChecking=no -i ../tools/ssh-key \
            -r ../reports/* \
            raskolnikov@sinusoid.es:public/misc/immer/reports/
    fi

before_install:
  - |
    openssl aes-256-cbc -K $encrypted_1c8d51d72e41_key \
        -iv $encrypted_1c8d51d72e41_iv \
        -in tools/ssh-key.enc \
        -out tools/ssh-key -d
